### ISSUE TITLE
win10 专业版 ninja1.9.0 编译 bee.lua出现问题

### ISSUE THREAD

**Issue by O30-l** [actboy168/luamake#2]
C:\User\Ai164\Desktop\luamake>ninja -f ninja/mingw.ninja
[0/4] cd 3rd/bee.lua && ninja -f ninja/mingw.ninja
FAILED: build/mingw/_/bee 
cd 3rd/bee.lua && ninja -f ninja/mingw.ninja
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

---------------------------------------------------------------------------------------------------

C:\User\Ai164\Desktop\luamake>cd 3rd\bee.lua
C:\User\Ai164\Desktop\luamake\3rd\bee.lua>ninja -f ninja/mingw.ninja
[1/67] Compile C build/mingw/obj/lua54/lapi.obj
FAILED: build/mingw/obj/lua54/lapi.obj 
gcc -MMD -MT build/mingw/obj/lua54/lapi.obj -MF build/mingw/obj/lua54/lapi.obj.d -std=c11 -O2 -Wall -DLUA_BUILD_AS_DLL -DLUAI_MAXCSTACK=1000 -DNDEBUG -o build/mingw/obj/lua54/lapi.obj -c 3rd/lua/src/lapi.c
CreateProcess failed: The system cannot find the file specified.
[2/67] Compile C build/mingw/obj/lua54/lauxlib.obj
FAILED: build/mingw/obj/lua54/lauxlib.obj 
gcc -MMD -MT build/mingw/obj/lua54/lauxlib.obj -MF build/mingw/obj/lua54/lauxlib.obj.d -std=c11 -O2 -Wall -DLUA_BUILD_AS_DLL -DLUAI_MAXCSTACK=1000 -DNDEBUG -o build/mingw/obj/lua54/lauxlib.obj -c 3rd/lua/src/lauxlib.c
CreateProcess failed: The system cannot find the file specified.
[3/67] Compile C build/mingw/obj/lua54/lbaselib.obj
FAILED: build/mingw/obj/lua54/lbaselib.obj 
gcc -MMD -MT build/mingw/obj/lua54/lbaselib.obj -MF build/mingw/obj/lua54/lbaselib.obj.d -std=c11 -O2 -Wall -DLUA_BUILD_AS_DLL -DLUAI_MAXCSTACK=1000 -DNDEBUG -o build/mingw/obj/lua54/lbaselib.obj -c 3rd/lua/src/lbaselib.c
CreateProcess failed: The system cannot find the file specified.
[4/67] Compile C build/mingw/obj/lua54/lcode.obj
FAILED: build/mingw/obj/lua54/lcode.obj 
gcc -MMD -MT build/mingw/obj/lua54/lcode.obj -MF build/mingw/obj/lua54/lcode.obj.d -std=c11 -O2 -Wall -DLUA_BUILD_AS_DLL -DLUAI_MAXCSTACK=1000 -DNDEBUG -o build/mingw/obj/lua54/lcode.obj -c 3rd/lua/src/lcode.c
CreateProcess failed: The system cannot find the file specified.
[5/67] Compile C build/mingw/obj/lua54/lctype.obj
FAILED: build/mingw/obj/lua54/lctype.obj 
gcc -MMD -MT build/mingw/obj/lua54/lctype.obj -MF build/mingw/obj/lua54/lctype.obj.d -std=c11 -O2 -Wall -DLUA_BUILD_AS_DLL -DLUAI_MAXCSTACK=1000 -DNDEBUG -o build/mingw/obj/lua54/lctype.obj -c 3rd/lua/src/lctype.c
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

子模块已经在克隆luamake 时一并克隆了 

$ git clone --recursive https://github.com/actboy168/luamake.git

luamake 为master分支
bee.lua 也是master

ninja 我直接下载的二进制文件

https://github.com/ninja-build/ninja/releases

已经添加环境变量

**Comment by actboy168** [comment]
你的终端找不到gcc
