### ISSUE TITLE
Error with bee.filesystem.exe_path on OpenBSD

### ISSUE THREAD

**Issue by lcheylus** [actboy168/luamake#28]
On OpenBSD-current (next 7.2 release) on amd64, with the recent commits (https://github.com/actboy168/luamake/commit/b806f0f2de7a759b9f8e19a759578e3aeecd54e5), `luamake` build is OK.

But I have an error when I try to exec `luamake` binary : 
```
$ ./luamake
Please use `./compile/install.sh`.
./luamake: ./scripts/writer.lua:910: exe_path: No such file or directory

stack traceback:
        [C]: in function 'bee.filesystem.exe_path'
        ./scripts/writer.lua:910: in upvalue 'get_luamake'
        ./scripts/writer.lua:972: in function 'writer.generate'
        ./scripts/simulator.lua:250: in function 'simulator.generate'
        ./scripts/action.lua:60: in function 'action.generate'
        ./scripts/command/make.lua:3: in main chunk
        [C]: in function 'dofile'
        ./scripts/main.lua:12: in local 'command'
        ./scripts/main.lua:29: in main chunk
        [C]: in function 'require'
        ./main.lua:8: in main chunk
        [C]: in ?
```

After some debug, it seems that `bee::path_helper::exe_path` function in `3rd/bee.lua/bee/utility/path_helper.cpp` is invalid for OpenBSD : 

- no special case with `if defined(__OpenBSD__)` 
- in generic case call to `fs::read_symlink("/proc/self/exe", ec)` (line 99) is not valid (no `/proc/self/exe` on OpenBSD).

**Comment by actboy168** [comment]
fixed in actboy168/bee.lua@733b50f623141100e16663119aa9710e33f99034

**Comment by lcheylus** [comment]
OK, problem solved after sources update and rebuild on OpenBSD/amd64

```bash
$ ./luamake
Please use `./compile/install.sh`.
ninja: no work to do.
```

Thanks, less than 15 minutes to fix this issue :+1:

**Comment by anoduck** [comment]
@lcheylus Have you tried building Luamake since 7.3 was released? Today, a [segmentation fault](https://github.com/actboy168/luamake/issues/33) was received immediately upon executing `ninja -f ./compile/ninja/openbsd.ninja`. Curious if you had discovered a workaround?
