### ISSUE TITLE
FAILED: build/linux/_/copy_bee_1 

### ISSUE THREAD

**Issue by BrunoXL** [actboy168/luamake#3]
I'm getting this error when I run my project:

 
	./luamake 
	[0/3] cd 3rd/bee.lua && ninja -f ninja/linux.ninja
	[1/2] mkdir -p build/linux/bin && cp bootstrap/main.lua build/linux/bin/main.lua
	[2/2] build/linux/bin/bootstrap test/test.lua
	...................................................................................
	Ran 83 tests in 0.162 seconds, 83 successes, 0 failures
	OK
	[2/3] cp 3rd/bee.lua/build/linux/bin/bootstrap luamake
	FAILED: build/linux/_/copy_bee_1 
	cp 3rd/bee.lua/build/linux/bin/bootstrap luamake
	cp: cannot create regular file 'luamake': Text file busy
	[3/3] cp 3rd/bee.lua/build/linux/bin/bee.so bee.so
	ninja: build stopped: subcommand failed.
	Segmentation fault (core dumped)

**Comment by actboy168** [comment]
Please compile with the steps of readme. luamake can't compile itself directly.

**Comment by BrunoXL** [comment]
Luamake seemed to compile ok:

    Ran 83 tests in 0.193 seconds, 83 successes, 0 failures
    OK
    [3/3] cp 3rd/bee.lua/build/linux/bin/bee.so bee.so

My problem is in step 4 in vscode installation instructions `Run task：Rebuild`. It returns me:

  > Executing task: luamake <

    /bin/bash: luamake: command not found
    The terminal process command '/bin/bash -c luamake' failed to launch (exit code: 127)
    Terminal will be reused by tasks, press any key to close it.

I'm running from the cloned repo (as step 3 indicates).

**Comment by actboy168** [comment]
You need to let bash known about luamake
