### ISSUE TITLE
拒绝访问

### ISSUE THREAD

**Issue by ly-lyl** [actboy168/luamake#35]
大佬，这是什么原因？

$ compile/install.sh
OS:             windows 10.0.18362
Arch:           x86_64
Compiler:       GCC 8.1.0
CRT:            libstdc++ 20180502
DEBUG:          false
.............................................................................
.................FF..
Failed tests:
-------------
1) filewatch.test_2
create_directories: 拒绝访问。
: "C:/Users/lmmxx/AppData/Local/Temp/test_bee/temp/"
stack traceback:
        bee.lua/test/test_filewatch.lua:20: in upvalue 'test'
        bee.lua/test/test_filewatch.lua:38: in upvalue 'filewatch.test_2'

2) filewatch.test_symlink
create_directories: 拒绝访问。
: "C:/Users/lmmxx/AppData/Local/Temp/test_bee/temp/"
stack traceback:
        bee.lua/test/test_filewatch.lua:86: in upvalue 'filewatch.test_symlink'

Ran 98 tests in 2.730 seconds, 96 successes, 2 failures
[0/1] Run test.
FAILED: build/mingw/obj/test.stamp
build/mingw/bin/bootstrap.exe bee.lua/test/test.lua --touch build/mingw/obj/test.stamp
ninja: build stopped: subcommand failed.

**Comment by actboy168** [comment]
低版本的mingw bug很多，升级到最新可能会好一点。虽然高版本的bug也有不少。

**Comment by ly-lyl** [comment]
我换了好几个版本都不行，然后我把这个测试代码注释掉了，但后面还有好多问题，例如“byte is not member of std”，“cannot find -lstdc++fs”，“could not convert 'XXXXX' to 'std::optional<XXXX>'’等。。。要不你直接把bee.dll发给我吧，我就想运行下MoeHero，但一直提醒缺少bee.filesystem。。。
还有，大佬，方便加个QQ吗？

**Comment by actboy168** [comment]
下载已发布的YDWE，或者使用YDWE自己的构建工具来编译。

**Comment by ly-lyl** [comment]
额...不懂，要不加个QQ626695684说吧！

**Comment by actboy168** [comment]
没有qq
