### ISSUE TITLE
gcc 10 build fail

### ISSUE THREAD

**Issue by Jackson-soft** [actboy168/luamake#5]
❯ ninja -f ninja/linux.ninja
[0/3] cd 3rd/bee.lua && ninja -f ninja/linux.ninja
[2/2] build/linux/bin/bootstrap test/test.lua
FAILED: build/linux/_/test 
build/linux/bin/bootstrap test/test.lua
OS:       	Linux
Arch:     	64
Compiler: 	GCC 10.1.0
CRT:      	libstdc++ 20200507
DEBUG:    	false
....
ninja: build stopped: subcommand failed.
FAILED: build/linux/_/bee 
cd 3rd/bee.lua && ninja -f ninja/linux.ninja
ninja: build stopped: subcommand failed.

**Comment by runiq** [comment]
The bee.lua submodule needs to be updated to incorporate https://github.com/actboy168/bee.lua/commit/8ae1c1944b4190a75f0dfc539a6ea5910bebdc5f.

**Comment by actboy168** [comment]
This is a gcc bug.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96040

**Comment by mcepl** [comment]
That bug is supposed to be fixed in 10.2:
```
luamake@stitny (master)$ ninja -v -f ninja/linux.ninja
[0/3] cd 3rd/bee.lua && ninja -f ninja/linux.ninja
[2/2] build/linux/bin/bootstrap test/test.lua
FAILED: build/linux/_/test
build/linux/bin/bootstrap test/test.lua
OS:       	Linux
Arch:     	64
Compiler: 	GCC 10.2.1
CRT:      	libstdc++ 20201202 glibc 2.33
DEBUG:    	false
..............................................terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
ninja: build stopped: subcommand failed.
FAILED: build/linux/_/bee
cd 3rd/bee.lua && ninja -f ninja/linux.ninja
ninja: build stopped: subcommand failed.
luamake@stitny (master)$
```

**Comment by actboy168** [comment]
@mcepl 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67791

**Comment by mcepl** [comment]
> @mcepl
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67791

Well, but that warning means that there is a bug in luamake (`Enable multithreading to use std::thread:`), doesn’t it?

**Comment by actboy168** [comment]
No. As the bug report said, gcc cannot handle `pthread_create` in dynamic libraries correctly.

**Comment by mcepl** [comment]
It was enough to build luamake to:
```sh
cd 3rd/bee.lua/
git checkout master
git pull
ninja -vvv -f ninja/linux.ninja
..
ninja -vvv -f ninja/linux.ninja
```
