### ISSUE TITLE
msvc_deps_prefix  = ？

### ISSUE THREAD

**Issue by car520120** [actboy168/luamake#9]
我执行了 compile\install.bat 报这个错，说没有配置  msvc_deps_prefix  可能是我安装了vs2019 vs2017需要配置的SDK路径？

**Comment by actboy168** [comment]
清空build目录试试

**Comment by car520120** [comment]
我试过每次删除 build 环境然后再在 vs2019  (x86\x64) tools prompt 中去执行，还是报一样的错来的？你有没有在 除了本地目录还有那些地方会有缓存？

**Comment by actboy168** [comment]
所有的缓存都在build里

**Comment by car520120** [comment]
试过的了，删除也没有用的，可能是ninja 的配置问题吧！
